services:
  nextjs:
    container_name: 'NewNextjsProject'
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs:dev
    networks:
      - network
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    healthcheck:
      test: ["CMD-SHELL", "node -e \"console.log('test')\""]
      interval: 5m
      timeout: 10s
      retries: 5
    stdin_open: true
    tty: true

networks:
  network:
    driver: bridge
