services:
  nextjs:
    container_name: 'NewNextjsProject'
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs:dev
    networks:
      - network
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

networks:
  network:
    driver: bridge
